version: "3"
services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOST: redis
    ports:
      - 8081:8081
