service: sf-assignment-pow
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221
  memorySize: 256
  logRetentionInDays: 14
  timeout: 29
  environment:
    REDIS_HOST: ${param:redis_host}
    REDIS_PORT: ${param:redis_port}

params:
  dev:
    redis_host: localhost
    redis_port: 6379

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    packager: yarn
    minify: false
    sourcemap: false
    target: node16
    watch:
      pattern: ['src/**/*.ts']

functions:
  graphql:
    handler: src/fn_graphql.handler
    events:
      - httpApi: '*'
